<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-OA26UOH" ignored="0" name="Test" tests="3" failures="1" timestamp="13 Jun 2021 12:48:45 GMT" time="0.035" errors="0">
  <testcase name="test1" time="0.005" classname="SeleAuto.TestSele"/>
  <testcase name="test2" time="0.0" classname="SeleAuto.TestSele"/>
  <testcase name="test3" time="0.002" classname="SeleAuto.TestSele">
    <failure type="java.lang.AssertionError" message="expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [3]
at SeleAuto.TestSele.test3(TestSele.java:21)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test -->
